# Generated by Django 6.0.2 on 2026-02-20 11:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedula_core', '0005_meeting_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='meeting',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
        ),
    ]
