# Generated by Django 6.0.2 on 2026-02-19 20:05
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedula_core", "0002_alter_meeting_participants"),
    ]

    operations = [
        migrations.RenameField(
            model_name="meeting",
            old_name="time",
            new_name="end_time",
        ),
        migrations.AddField(
            model_name="meeting",
            name="location",
            field=models.CharField(default=None, null=True, blank=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meeting",
            name="start_time",
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
    ]
